config/routes.rb
Freemarket::Application.routes.draw do
  resources :things do
    post 'want'
  end

  resources :wants, :only => [:show] do
    resources :messages, :only => [:create]
    post 'give'
  end

  get "home/index"
  devise_for :users, :controllers => {:registrations => "users/registrations", :passwords => "users/passwords"}
  root 'home#index'
  resources :users, :only => [:show, :index]

  post 'notifications/update'
end

app/models/thing.rb
class Thing < ActiveRecord::Base
  belongs_to :user
  has_many :wants

  def is_given?
    self.given ? 'Yes' : 'Nope'
  end
end

app/controllers/things_controller.rb
class ThingsController < ApplicationController
  before_action :set_thing, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, only: [:new, :create, :update, :want]

  # GET /things
  # GET /things.json
  def index
    @things = Thing.all
  end

  # GET /things/1
  # GET /things/1.json
  def show
  end

  # GET /things/new
  def new
    @thing = Thing.new
  end

  # GET /things/1/edit
  def edit
  end

  # POST /things
  # POST /things.json
  def create
    @thing = Thing.new(thing_params)
    @thing.user = current_user

    respond_to do |format|
      if @thing.save
        format.html { redirect_to @thing, notice: 'Thing was successfully created.' }
        format.json { render action: 'show', status: :created, location: @thing }
      else
        format.html { render action: 'new' }
        format.json { render json: @thing.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /things/1
  # PATCH/PUT /things/1.json
  def update
    return unless can? :manage, @thing
    respond_to do |format|
      if @thing.update(thing_params)
        format.html { redirect_to @thing, notice: 'Thing was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @thing.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /things/1
  # DELETE /things/1.json
  def destroy
    @thing.destroy
    respond_to do |format|
      format.html { redirect_to things_url }
      format.json { head :no_content }
    end
  end

  def want
    @thing = Thing.find(params[:thing_id])
    Want.create_want @thing, current_user, message_params[:text]
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_thing
      @thing = Thing.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def thing_params
      params.require(:thing).permit(:name, :description)
    end

    def message_params
      params.require(:message).permit(:text)
    end
end

app/helpers/things_helper.rb
module ThingsHelper
  def thing_link(thing)
    link_to thing.name, thing
  end
end

app/views/things/_form.html.erb
<%= form_for(@thing) do |f| %>
  <% if @thing.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@thing.errors.count, "error") %> prohibited this thing from being saved:</h2>

      <ul>
      <% @thing.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_field :description %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/things/edit.html.erb
<h1>Editing thing</h1>

<%= render 'form' %>

app/views/things/index.html.erb
<h1>Listing things</h1>

<%= render :partial => 'things/partials/things', :locals => {
                   :things => @things
           } %>

<br>

<%= link_to 'New Thing', new_thing_path %>

app/views/things/new.html.erb
<h1>New thing</h1>

<%= render 'form' %>

<%= link_to 'Back', things_path %>

app/views/things/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @thing.name %>
</p>

<p>
  <strong>Given:</strong>
  <%= @thing.given %>
</p>

<p>
  <strong>Description:</strong>
  <%= @thing.description %>
</p>

<p>
  <strong>Author:</strong>
  <%= link_to @thing.user.username, @thing.user %>
</p>
<%= render :partial => 'things/partials/want_button' %>


<%= link_to 'Edit', edit_thing_path(@thing) if can? :manage, @thing%>
<%= link_to 'Back', things_path if can? :manage, @thing %>

app/views/things/want.js.erb
$('#myModal').modal('hide');
$('#want-button').replaceWith("<%= escape_javascript(render :partial => 'things/partials/want_button') %>");