config/routes.rb
Freemarket::Application.routes.draw do
  resources :things do
    post 'want'
  end

  resources :wants, :only => [:show] do
    resources :messages, :only => [:create]
    post 'give'
  end

  get "home/index"
  devise_for :users, :controllers => {:registrations => "users/registrations", :passwords => "users/passwords"}
  root 'home#index'
  resources :users, :only => [:show, :index]

  post 'notifications/update'
end

app/models/want.rb
class Want < ActiveRecord::Base
  belongs_to :thing
  belongs_to :user
  has_many :messages

  before_create :init


  def self.create_want(thing, user, text)
    want = thing.wants.create(:user => user)
    Message.create(:text => text, :from => user, :to => thing.user, :want => want)
    RelatedEvent.notify_all want, :created, user
  end

  def init
    self.accepted = false if self.accepted.nil?
    self.finished = false if self.finished.nil?
  end

  def finish
    ActiveRecord::Base.transaction do
      author = self.thing.user
      self.thing.wants.each do |want|
        unless want == self
          want.accepted = false
          want.finished = true
          want.save
          RelatedEvent.notify_all want, :finished, author #same as current_user
        end
      end
      self.accepted = true
      self.finished = true
      self.save
      RelatedEvent.notify_all self, :finished, author
      self.thing.given = true
      self.thing.save
    end
  end
end

app/controllers/wants_controller.rb
class WantsController < ApplicationController
  before_action :set_want, only: [:show]

  def give
    @want = Want.find(params[:want_id])
    @want.finish
  end

  private
  # Use callbacks to share common setup or constraints between actions.
  def set_want
    @want = Want.find(params[:id])
  end
end

app/views/wants/partials/_finish.html.erb
<div id="give-thing" class="">
  <% if want.finished? %>
      <%= thing_link want.thing %> ужо ў <%= user_link want.user %>
  <% else %>

      <%= form_tag(want_give_path(want), :remote => true, :method => 'post') do %>
          <%= submit_tag 'Рэч аддадзена', :class => 'btn btn-large btn-success btn-block' %>
      <% end %>

  <% end %>
</div>

app/views/wants/partials/_state.html.erb
<% if want.finished? %>
    <% if want.accepted? %>
        <%= thing_link want.thing %> ужо ў Вас
    <% else %>
        Нажаль, пайшло не Вам
    <% end %>
<% else %>
    чэл думае
    <div class="progress active progress-striped">
      <div class="bar" style="width: 50%"></div>
    </div>
<% end %>