config/routes.rb
Freemarket::Application.routes.draw do
  resources :things do
    post 'want'
  end

  resources :wants, :only => [:show] do
    resources :messages, :only => [:create]
    post 'give'
  end

  get "home/index"
  devise_for :users, :controllers => {:registrations => "users/registrations", :passwords => "users/passwords"}
  root 'home#index'
  resources :users, :only => [:show, :index]

  post 'notifications/update'
end

app/models/thing.rb
class Thing < ActiveRecord::Base
  belongs_to :user
  has_many :wants

  def is_given?
    self.given ? 'Yes' : 'Nope'
  end
end

app/controllers/things_controller.rb
class ThingsController < ApplicationController
  before_action :set_thing, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, only: [:new, :create, :update, :want]

  # GET /things
  # GET /things.json
  def index
    @things = Thing.all
  end

  # GET /things/1
  # GET /things/1.json
  def show
  end

  # GET /things/new
  def new
    @thing = Thing.new
  end

  # GET /things/1/edit
  def edit
  end

  # POST /things
  # POST /things.json
  def create
    @thing = Thing.new(thing_params)
    @thing.user = current_user

    respond_to do |format|
      if @thing.save
        format.html { redirect_to @thing, notice: 'Thing was successfully created.' }
        format.json { render action: 'show', status: :created, location: @thing }
      else
        format.html { render action: 'new' }
        format.json { render json: @thing.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /things/1
  # PATCH/PUT /things/1.json
  def update
    return unless can? :manage, @thing
    respond_to do |format|
      if @thing.update(thing_params)
        format.html { redirect_to @thing, notice: 'Thing was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @thing.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /things/1
  # DELETE /things/1.json
  def destroy
    @thing.destroy
    respond_to do |format|
      format.html { redirect_to things_url }
      format.json { head :no_content }
    end
  end

  def want
    @thing = Thing.find(params[:thing_id])
    Want.create_want @thing, current_user, message_params[:text]
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_thing
      @thing = Thing.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def thing_params
      params.require(:thing).permit(:name, :description)
    end

    def message_params
      params.require(:message).permit(:text)
    end
end

app/helpers/things_helper.rb
module ThingsHelper
  def thing_link(thing)
    link_to thing.name, thing
  end
end

app/views/things/partials/_things.html.erb
<% if things.any? %>
<table>
  <thead>
  <tr>
    <th style="width: 20%;">Name</th>
    <th>Given</th>
    <th>Description</th>
    <th>By</th>
  </tr>
  </thead>

  <tbody>
  <% things.each do |thing| %>
      <tr>
        <td><%= thing_link thing %></td>
        <td><%= thing.is_given? %></td>
        <td><%= thing.description %></td>
        <td><%= user_link thing.user %></td>
      </tr>
  <% end %>
  </tbody>
</table>

<% else %>
No things yet
<% end %>

app/views/things/partials/_want_button.html.erb
<div id="want-button">
  <% if @thing.given? %>
  Ужо аададзена
  <% else %>
      <% if user_signed_in? %>
          <% unless can? :manage, @thing %>
              <% wants = @thing.wants.where(:user => current_user) %>
              <% if wants.empty? %>
                  <a href="#myModal" role="button" class="btn btn-large btn-danger" data-toggle="modal">Хачу!</a>

                  <!-- Modal -->
                  <div id="myModal" class="modal hide fade" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
                    <div class="modal-header">
                      <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
                      <h3 id="myModalLabel">Паведамленьне напішыце</h3>
                    </div>
                    <div class="modal-body">
                      <%= form_for(Message.new, remote: true, url: thing_want_path(@thing), method: :post) do |f| %>
                          <div class="field">
                            <label>
                              <%= f.text_area :text, class: 'input-block-level', rows: 4, placeholder: 'Тутака' %>
                            </label>
                          </div>
                          <div class="field">
                            <%= f.submit 'Даслаць', :class => 'btn btn-success btn-large pull-right' %>
                          </div>
                      <% end %>
                    </div>
                  </div>
              <% else %>
                  <%= link_to 'Трэкнуць прогрэс', wants[0], :class => 'btn btn-large btn-info' %>
              <% end %>
          <% end %>
      <% else %>
          <%= link_to 'Увайдзіце', new_user_session_path %> каб узяць
      <% end %>
  <% end %>
</div>