config/routes.rb
Freemarket::Application.routes.draw do
  resources :things do
    post 'want'
  end

  resources :wants, :only => [:show] do
    resources :messages, :only => [:create]
    post 'give'
  end

  get "home/index"
  devise_for :users, :controllers => {:registrations => "users/registrations", :passwords => "users/passwords"}
  root 'home#index'
  resources :users, :only => [:show, :index]

  post 'notifications/update'
end

app/models/want.rb
class Want < ActiveRecord::Base
  belongs_to :thing
  belongs_to :user
  has_many :messages

  before_create :init


  def self.create_want(thing, user, text)
    want = thing.wants.create(:user => user)
    Message.create(:text => text, :from => user, :to => thing.user, :want => want)
    RelatedEvent.notify_all want, :created, user
  end

  def init
    self.accepted = false if self.accepted.nil?
    self.finished = false if self.finished.nil?
  end

  def finish
    ActiveRecord::Base.transaction do
      author = self.thing.user
      self.thing.wants.each do |want|
        unless want == self
          want.accepted = false
          want.finished = true
          want.save
          RelatedEvent.notify_all want, :finished, author #same as current_user
        end
      end
      self.accepted = true
      self.finished = true
      self.save
      RelatedEvent.notify_all self, :finished, author
      self.thing.given = true
      self.thing.save
    end
  end
end

app/controllers/notifications_controller.rb
class NotificationsController < ApplicationController
  def update
    @event = RelatedEvent.find(params[:id])
    if @event.reader == current_user
      @event.read = true
      @event.save
    end
    render :nothing => true
  end
end

app/controllers/wants_controller.rb
class WantsController < ApplicationController
  before_action :set_want, only: [:show]

  def give
    @want = Want.find(params[:want_id])
    @want.finish
  end

  private
  # Use callbacks to share common setup or constraints between actions.
  def set_want
    @want = Want.find(params[:id])
  end
end

app/helpers/notifications_helper.rb
module NotificationsHelper
end

app/views/wants/notifications/_want.html.erb
<li>
  <%= link_to "#{want.thing.name} хоча узяць #{want.user.username}", want_path(want) %>
</li>

app/views/wants/notifications/_wants.html.erb
<div id="notifications" style="display: inline-block;">
  <% wants = current_user.pending_wants %>
  <% if wants.any? %>
      <div class="dropdown">
        <a class="dropdown-toggle" id="drop4" role="button" data-toggle="dropdown" href="#">Notifications<b class="caret"></b></a>
        <ul id="menu1" class="dropdown-menu" style=" font-size: small;">
          <%= render :partial => 'wants/notifications/want', :collection => wants %>
        </ul>
      </div>
  <% else %>
      No notifications
  <% end %>
</div>